apiVersion: apps/v1
kind: Deployment
metadata:
  name: als-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: als
  template:
    metadata:
      labels:
        app: als
    spec:
      containers:
        - name: als
          image: sethm/envoy-als-example:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: als
spec:
  selector:
    app: als
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080